FROM python:3.12.3-slim


WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*


COPY . .

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    llama-cpp-python \
    pydantic

EXPOSE 8000

CMD ["uvicorn", "deploy.app:app", "--host", "0.0.0.0", "--port", "8000"]



