import asyncio
from autogen_agentchat.messages import TextMessage
from config.llm_client import get_model_client
from orchestrator.planner import create_planner
from agents.worker_agent import create_worker_agent
from agents.reflection_agent import create_reflection_agent
from agents.validator import create_validator_agent


def extract_tasks(plan_text: str):
    tasks = []
    for line in plan_text.split("\n"):
        line = line.strip()
        if line.startswith(("1.", "2.", "3.", "4.")):
            task = line.split(". ", 1)[-1].strip()
            if task:
                tasks.append(task)
    return tasks


async def run_workers_parallel(model_client, tasks):
    workers = [create_worker_agent(model_client) for _ in tasks]

    async def run_task(worker, task_text):
        try:
            result = await worker.run(
                task=TextMessage(content=task_text, source="planner")
            )
            return result.messages[-1].content
        except Exception as e:
            return f"WORK RESULT\n- Error: {str(e)}"

    results = await asyncio.gather(
        *[run_task(w, t) for w, t in zip(workers, tasks)]
    )

    return results


async def main():

    model_client = get_model_client()

    planner = create_planner(model_client)
    reflection = create_reflection_agent(model_client)
    validator = create_validator_agent(model_client)

    query = input("Enter your question: ")


    plan_result = await planner.run(
        task=TextMessage(content=query, source="user")
    )
    
    plan = plan_result.messages[-1].content
    print("\n PLAN \n")
    print(plan)

    tasks = extract_tasks(plan)

    if not tasks:
        print("No tasks generated by planner. Exiting.")
        return

    worker_outputs = await run_workers_parallel(model_client, tasks)

    print("\n WORKER OUTPUTS (PARALLEL) \n")
    for i, output in enumerate(worker_outputs):
        print(f" Task {i+1} ")
        print(output)
        print()

    combined_worker_output = "\n\n".join(worker_outputs)

    reflection_result = await reflection.run(
        task=TextMessage(content=combined_worker_output, source="worker")
    )

    reflection_output = reflection_result.messages[-1].content
    print("\n REFLECTION \n")
    print(reflection_output)

    validator_result = await validator.run(
        task=TextMessage(content=reflection_output, source="reflection")
    )
    final_answer = validator_result.messages[-1].content
    print("\n FINAL ANSWER \n")
    print(final_answer)


if __name__ == "__main__":
    asyncio.run(main())